n1 = input('digite um número:')
print(type(n1))
#print(n1.isdigit())
print('ele é um número?', n1.isnumeric())
print('ele é uma letra?', n1.isalpha())
print('ele é um digito?', n1.isdigit())
print('ele é um número decimal?', n1.isdecimal())
print('ele está escrito somente com letras maiúsculas?', n1.isupper())
print('ele está escrito somente com letras minusculas?', n1.islower())
print('ele é um espaço?', n1.isspace())
print('ele é um título?', n1.istitle())
print('ele é um número junto com uma letra, vice-versa?', n1.isalnum())